# Generated by Django 6.0.2 on 2026-02-24 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspaces.workspace', verbose_name='Workspace'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace'], name='projects_pr_workspa_788011_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='unique_key_per_workspace'),
        ),
    ]
