# Generated by Django 2.2.10 on 2020-08-15 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0003_auto_20200815_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'get_latest_by': 'created_at', 'ordering': ['owner', 'name'], 'verbose_name': 'workspace', 'verbose_name_plural': 'workspaces'},
        ),
        migrations.AddField(
            model_name='workspace',
            name='slug',
            field=models.SlugField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='workspace',
            unique_together={('slug', 'owner')},
        ),
    ]
