# Generated by Django 4.2.10 on 2024-03-02 13:01

from django.db import migrations


def create_default_workspace(apps, schema_editor):
    """
    Creates the default workspace and add all the users to it
    """

    User = apps.get_model("users", "User")

    if User.objects.count() == 0:
        # No users, nothing to do: the workspace will be created when the first user is created
        return

    # Get the first superuser or admin user
    admin_user = User.objects.filter(is_superuser=True).first()

    if admin_user is None:
        admin_user = User.objects.filter(is_staff=True).first()

    if admin_user is None:
        admin_user = User.objects.first()

        Workspace = apps.get_model("workspaces", "Workspace")
        default_workspace = Workspace.objects.create(
            name="Default Workspace", slug="default-workspace", owner=admin_user
        )

        # Now add all the users to the default workspace
        for user in User.objects.all():
            default_workspace.members.add(user)


def delete_default_workspace(apps, schema_editor):
    Workspace = apps.get_model("workspaces", "Workspace")
    Workspace.objects.filter(slug="default-workspace").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0004_auto_20200815_1608"),
    ]

    operations = [
        migrations.RunPython(create_default_workspace, reverse_code=delete_default_workspace),
    ]
