# Generated by Django 2.2.1 on 2019-05-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20190520_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstory',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
