# Generated by Django 2.2.1 on 2019-05-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20190520_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epic',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='story',
            name='tags',
        ),
    ]
