# Generated by Django 6.0.2 on 2026-02-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(blank=True, db_index=True, help_text='Auto-generated unique identifier (e.g., SPRINT-1).', max_length=50, verbose_name='Key')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('goal', models.TextField(blank=True, help_text='The sprint goal or objective.', verbose_name='Goal')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='planning', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(db_index=True, verbose_name='Start Date')),
                ('end_date', models.DateField(db_index=True, verbose_name='End Date')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Planned capacity in story points.', null=True, verbose_name='Capacity')),
                ('committed_points', models.PositiveIntegerField(default=0, help_text='Total points committed at sprint start.', verbose_name='Committed Points')),
                ('completed_points', models.PositiveIntegerField(default=0, help_text='Total points completed.', verbose_name='Completed Points')),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
                'ordering': ['-start_date', 'name'],
            },
        ),
    ]
