# Generated by Django 6.0.2 on 2026-02-21 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sprints', '0002_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='workspaces.workspace', verbose_name='Workspace'),
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='unique_sprint_key_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('workspace',), name='unique_active_sprint_per_workspace'),
        ),
    ]
