from .bulk import ProjectBulkDeleteView, ProjectBulkLeadView, ProjectBulkMoveView, ProjectBulkStatusView
from .crud import (
    ProjectCloneView,
    ProjectCreateView,
    ProjectDeleteView,
    ProjectDetailInlineEditView,
    ProjectDetailView,
    ProjectEpicChildrenView,
    ProjectEpicCreateView,
    ProjectEpicsEmbedView,
    ProjectIssueCreateView,
    ProjectListView,
    ProjectMilestoneCreateView,
    ProjectMoveView,
    ProjectOrphanIssuesEmbedView,
    ProjectRowInlineEditView,
    ProjectUpdateView,
)
from .history import ProjectHistoryView

__all__ = [
    "ProjectBulkDeleteView",
    "ProjectBulkLeadView",
    "ProjectBulkMoveView",
    "ProjectBulkStatusView",
    "ProjectCloneView",
    "ProjectCreateView",
    "ProjectDeleteView",
    "ProjectDetailInlineEditView",
    "ProjectDetailView",
    "ProjectEpicChildrenView",
    "ProjectEpicCreateView",
    "ProjectEpicsEmbedView",
    "ProjectHistoryView",
    "ProjectIssueCreateView",
    "ProjectListView",
    "ProjectMilestoneCreateView",
    "ProjectMoveView",
    "ProjectOrphanIssuesEmbedView",
    "ProjectRowInlineEditView",
    "ProjectUpdateView",
]
