# Generated by Django 2.2.1 on 2019-05-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalstory",
            name="sprint",
        ),
        migrations.RemoveField(
            model_name="story",
            name="sprint",
        ),
        migrations.DeleteModel(
            name="HistoricalSprint",
        ),
        migrations.DeleteModel(
            name="Sprint",
        ),
    ]
