# Generated by Django 2.2.1 on 2019-05-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20190525_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='epicstate',
            name='stype',
            field=models.CharField(choices=[('u', 'Unstarted'), ('s', 'Started'), ('d', 'Done')], db_index=True, default='u', max_length=1),
        ),
        migrations.AddField(
            model_name='storystate',
            name='stype',
            field=models.CharField(choices=[('u', 'Unstarted'), ('s', 'Started'), ('d', 'Done')], db_index=True, default='u', max_length=1),
        ),
    ]
