# Generated by Django 4.2.10 on 2024-02-23 09:10

from django.db import migrations


story_slug_name_list = [
    ("pl", "Planning"),
    ("pr", "Prioritized & Ready"),
    ("ip", "In Progress"),
    ("qa", "In QA"),
    ("3p", "Waiting for 3rd Party"),
    ("dn", "Done"),
    ("wd", "Won't Do"),
]

epic_slug_name_list = [
    ("pl", "Planning"),
    ("pr", "Prioritized & Ready"),
    ("ip", "In Progress"),
    ("dn", "Done"),
]


def create_story_states(apps, schema_editor):
    StoryState = apps.get_model("stories", "StoryState")

    for slug, name in story_slug_name_list:
        StoryState.objects.get_or_create(slug=slug, defaults={"name": name})

    EpicState = apps.get_model("stories", "EpicState")

    for slug, name in epic_slug_name_list:
        EpicState.objects.get_or_create(slug=slug, defaults={"name": name})


def remove_story_states(apps, schema_editor):
    StoryState = apps.get_model("stories", "StoryState")

    for slug, _ in story_slug_name_list:
        StoryState.objects.filter(slug=slug).delete()

    EpicState = apps.get_model("stories", "EpicState")

    for slug, _ in epic_slug_name_list:
        EpicState.objects.filter(slug=slug).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0010_alter_historicalepic_options_and_more"),
    ]

    operations = [
        migrations.RunPython(create_story_states, remove_story_states),
    ]
