# Generated by Django 6.0.2 on 2026-02-21 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('key', models.CharField(blank=True, db_index=True, help_text='Auto-generated unique identifier (e.g., PROJ-1-123).', max_length=50, verbose_name='Key')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planning', 'Planning'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('in_review', 'In Review'), ('done', 'Done'), ('wont_do', "Won't Do"), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20, verbose_name='Priority')),
                ('estimated_points', models.PositiveIntegerField(blank=True, help_text='Story points or effort estimate. Only meaningful on work items (Story, Bug, Chore).', null=True, verbose_name='Estimated Points')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Due Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(blank=True, db_index=True, help_text='Auto-generated unique identifier (e.g., M-1).', max_length=50, verbose_name='Key')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planning', 'Planning'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('in_review', 'In Review'), ('done', 'Done'), ('wont_do', "Won't Do"), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Due Date')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20, verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('wont_do', "Won't Do")], db_index=True, default='todo', max_length=20, verbose_name='Status')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Subtask',
                'verbose_name_plural': 'Subtasks',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('baseissue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='issues.baseissue')),
                ('severity', models.CharField(choices=[('trivial', 'Trivial'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical'), ('blocker', 'Blocker')], db_index=True, default='minor', max_length=20, verbose_name='Severity')),
            ],
            options={
                'verbose_name': 'Bug',
                'verbose_name_plural': 'Bugs',
            },
            bases=('issues.baseissue', models.Model),
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('baseissue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='issues.baseissue')),
            ],
            options={
                'verbose_name': 'Chore',
                'verbose_name_plural': 'Chores',
            },
            bases=('issues.baseissue', models.Model),
        ),
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('baseissue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='issues.baseissue')),
            ],
            options={
                'verbose_name': 'Epic',
                'verbose_name_plural': 'Epics',
            },
            bases=('issues.baseissue',),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('baseissue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='issues.baseissue')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
            bases=('issues.baseissue', models.Model),
        ),
    ]
