# Generated by Django 6.0.2 on 2026-02-21 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('issues', '0001_initial'),
        ('projects', '0001_initial'),
        ('sprints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baseissue',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL, verbose_name='Assignee'),
        ),
        migrations.AddField(
            model_name='baseissue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='baseissue',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='baseissue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_milestones', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_milestones', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'issues'), ('model__in', ['story', 'bug', 'chore'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='bug',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='sprints.sprint', verbose_name='Sprint'),
        ),
        migrations.AddField(
            model_name='chore',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='sprints.sprint', verbose_name='Sprint'),
        ),
        migrations.AddField(
            model_name='epic',
            name='milestone',
            field=models.ForeignKey(blank=True, help_text='Optionally link this epic to a project-level milestone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epics', to='issues.milestone', verbose_name='Milestone'),
        ),
        migrations.AddField(
            model_name='story',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='sprints.sprint', verbose_name='Sprint'),
        ),
        migrations.AddIndex(
            model_name='baseissue',
            index=models.Index(fields=['project', 'polymorphic_ctype'], name='issues_base_project_17aa5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='baseissue',
            constraint=models.UniqueConstraint(fields=('project', 'key'), name='unique_issue_key_per_project'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.UniqueConstraint(fields=('project', 'key'), name='unique_milestone_key_per_project'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['content_type', 'object_id'], name='issues_subt_content_0feabb_idx'),
        ),
    ]
