# Generated by Django 6.0.2 on 2026-03-04 12:00

from django.db import migrations


def migrate_subtasks_to_baseissue(apps, schema_editor):
    """
    Migrate existing Subtask records to BaseIssue children.

    Maps Subtask fields to BaseIssue:
    - title -> title
    - status: TODO -> READY, IN_PROGRESS -> IN_PROGRESS, DONE -> DONE, WONT_DO -> WONT_DO
    - project -> copied from parent
    - key -> auto-generated
    - priority -> MEDIUM
    - assignee -> None
    - due_date -> None
    - estimated_points -> None
    - description -> ""
    """
    Subtask = apps.get_model("issues", "Subtask")
    BaseIssue = apps.get_model("issues", "BaseIssue")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # Status mapping from SubtaskStatus to IssueStatus (using string values)
    status_map = {
        "todo": "ready",  # Subtask TODO becomes READY (actionable)
        "in_progress": "in_progress",
        "done": "done",
        "wont_do": "wont_do",
    }

    # Get all subtasks ordered by position to maintain order
    subtasks = Subtask.objects.all().order_by("content_type_id", "object_id", "position", "created_at")

    for subtask in subtasks:
        # Get parent using content_type and object_id (GenericForeignKey)
        try:
            parent_ct = ContentType.objects.get(pk=subtask.content_type_id)
            parent_model = parent_ct.model_class()
            if parent_model is None:
                continue
            parent = parent_model.objects.get(pk=subtask.object_id)
        except ContentType.DoesNotExist, AttributeError, Exception:
            continue

        # Map status
        issue_status = status_map.get(subtask.status, "ready")

        # Create BaseIssue as child of parent
        # Use add_child which handles tree path generation
        issue = BaseIssue(
            project=parent.project,
            title=subtask.title,
            status=issue_status,
            priority="medium",  # IssuePriority.MEDIUM as string
            assignee=None,
            due_date=None,
            estimated_points=None,
            description="",
            created_by=parent.created_by if hasattr(parent, "created_by") else None,
        )

        # Set timestamps to preserve history
        issue.created_at = subtask.created_at
        issue.updated_at = subtask.updated_at

        # Add as child to parent (this sets the key and path)
        parent.add_child(instance=issue)


def reverse_migrate_subtasks(apps, schema_editor):
    """
    Reverse migration: delete all BaseIssue records that were created as subtasks.
    Since there's no way to perfectly restore subtasks, we just delete them.
    """
    BaseIssue = apps.get_model("issues", "BaseIssue")
    Story = apps.get_model("issues", "Story")
    Bug = apps.get_model("issues", "Bug")
    Chore = apps.get_model("issues", "Chore")

    # This is a destructive reverse - we can't perfectly recreate subtasks
    # So we delete all children of work items
    for parent in list(Story.objects.all()) + list(Bug.objects.all()) + list(Chore.objects.all()):
        children = parent.get_children()
        if children:
            children.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(
            migrate_subtasks_to_baseissue,
            reverse_code=reverse_migrate_subtasks,
        ),
    ]
