# Generated by Django 6.0.2 on 2026-03-04 15:00

from django.db import migrations


class Migration(migrations.Migration):
    """Delete the Subtask model and its table after migrating data to BaseIssue children."""

    dependencies = [
        ("issues", "0003_migrate_subtasks_to_tree"),
    ]

    operations = [
        # Delete the Subtask model
        migrations.DeleteModel(
            name="Subtask",
        ),
    ]
