# Generated by Django 6.0.2 on 2026-03-04 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_cleanup_subtask_contenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('baseissue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='issues.baseissue')),
            ],
            options={
                'verbose_name': 'Subtask',
                'verbose_name_plural': 'Subtasks',
            },
            bases=('issues.baseissue',),
        ),
    ]
