# Generated by Django 6.0.2 on 2026-03-04 23:53

from django.db import migrations


def convert_baseissue_subtasks_to_subtask(apps, schema_editor):
    """
    Convert existing BaseIssue instances that are children of work items
    (Story, Bug, Chore) to Subtask instances.

    These were previously created as BaseIssue but should be Subtask to use
    the new polymorphic type.
    """
    ContentType = apps.get_model("contenttypes", "ContentType")
    BaseIssue = apps.get_model("issues", "BaseIssue")
    Subtask = apps.get_model("issues", "Subtask")

    # Get the Subtask content type
    subtask_ct = ContentType.objects.get_for_model(Subtask)

    # Get content type IDs for work items
    story_ct = ContentType.objects.get_for_model(apps.get_model("issues", "Story"))
    bug_ct = ContentType.objects.get_for_model(apps.get_model("issues", "Bug"))
    chore_ct = ContentType.objects.get_for_model(apps.get_model("issues", "Chore"))

    # Get all parent IDs for stories, bugs, and chores
    parent_pks = BaseIssue.objects.filter(polymorphic_ctype__in=[story_ct, bug_ct, chore_ct]).values_list(
        "pk", flat=True
    )

    if not parent_pks:
        print("No work items found. No subtasks to convert.")
        return

    # Find all BaseIssue instances that are children of these work items
    # Using treebeard path prefix matching - children have path starting with parent.path + stree
    # A work item at depth 1 (story/bug/chore) has children at path starting with that path

    # Build a query for children of the given parents
    # Each parent has a path, and children have paths starting with parent_path + "0" * steplen
    from apps.issues.models import BaseIssue as RealBaseIssue

    converted_count = 0
    subtasks_to_update = []
    steplen = RealBaseIssue.steplen

    for parent_pk in parent_pks:
        # Get parent path
        parent = BaseIssue.objects.get(pk=parent_pk)
        parent_path = parent.path

        # Find children: path starts with parent_path and has exactly steplen more characters
        # Treebeard MP algorithm: children paths are parent_path + "0" * steplen + sequence
        children = BaseIssue.objects.filter(
            path__startswith=parent_path,
            path__regex=r"^" + parent_path + r"[0-9]{" + str(steplen) + r"}$",
        ).exclude(polymorphic_ctype=subtask_ct)

        for child in children:
            subtasks_to_update.append(child.pk)
            converted_count += 1

    # Update all subtasks at once
    if subtasks_to_update:
        BaseIssue.objects.filter(pk__in=subtasks_to_update).update(polymorphic_ctype=subtask_ct)

    if converted_count > 0:
        print(f"Converted {converted_count} BaseIssue subtasks to Subtask instances")


def reverse_convert_subtasks_to_baseissue(apps, schema_editor):
    """Reverse: convert Subtask instances back to BaseIssue."""
    ContentType = apps.get_model("contenttypes", "ContentType")
    BaseIssue = apps.get_model("issues", "BaseIssue")

    # Get the BaseIssue content type
    baseissue_ct = ContentType.objects.get_for_model(BaseIssue)

    # Convert all Subtask instances back to BaseIssue
    Subtask = apps.get_model("issues", "Subtask")
    subtasks = Subtask.objects.all()

    converted_count = subtasks.count()
    Subtask.objects.update(polymorphic_ctype=baseissue_ct)

    if converted_count > 0:
        print(f"Converted {converted_count} Subtask instances back to BaseIssue")


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0006_subtask"),
    ]

    operations = [
        migrations.RunPython(
            convert_baseissue_subtasks_to_subtask,
            reverse_convert_subtasks_to_baseissue,
        ),
    ]
