# Generated by Django 2.2.10 on 2020-08-15 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0004_auto_20200815_1608"),
        ("sprints", "0006_auto_20190630_1552"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsprint",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="workspaces.Workspace",
            ),
        ),
        migrations.AddField(
            model_name="sprint",
            name="workspace",
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to="workspaces.Workspace"),
            preserve_default=False,
        ),
    ]
