# Generated by Django 4.2.10 on 2024-03-02 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sprints", "0008_alter_historicalsprint_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sprint",
            options={
                "get_latest_by": "created_at",
                "ordering": ["starts_at", "-updated_at"],
                "verbose_name": "sprint",
                "verbose_name_plural": "sprints",
            },
        ),
    ]
